### ISSUE TITLE
Issues adding the module to projucer

### ISSUE THREAD

**Issue by dataexcess** [adamski/RestRequest#5]
Hello,

Looks like an awesome module. When I manually add 'folder' in the module option projucer says "This wasn't a valid module folder"
Putting the module folder in the JUCE module folder also does not work...

Can you help? 
(I am on the latest version of JUCE)

Thank you!

**Comment by adamski** [comment]
I think the folder you add to Projucer is the one containing the top header file, in this case `rest_request.h`.

I don't use Projucer much these days.

You can also just copy the header file to your project.

**Comment by dataexcess** [comment]
Yes, that's what I am doing. 
I don't get it.

Are you sure you are on the latest juce version?

**Comment by adamski** [comment]
I've had similar issue with Projucer before. As I said I don't use Projucer these days and don't have a project with which to verify. Have you tried with another 3rd party JUCE module?

**Comment by dataexcess** [comment]
No I have not it's the first time I'm trying to add a module...
Is there a way I can use it without importing as a module?

**Comment by adamski** [comment]
Yes, as I said above you can just add the header file to your project https://github.com/adamski/RestRequest/blob/master/Source/RestRequest.h

**Comment by dataexcess** [comment]
No, simply dragging the RestRequest.h into the project source does not work.
When including it in my PluginEditor.h for example it says:

#include "RestRequest.h" => 'RestRequest.h' file not found

**Comment by adamski** [comment]
This sounds like an issue with your project file structure.

**Comment by dataexcess** [comment]
Ok I got it working!

I had to combine your rest_request.h code (all the includes etc.) with your RestRequest.h code.
Sorry for the hassle!

**Comment by dataexcess** [comment]
Ok no, what really made it work is, I made a new .h file in the projucer and simply copied and pasted the content of the RestRequest.h file in there... That was the only way to make it work.
Looking forward to use it!
